### PR TITLE
Implement Support Vector Machine

### PR DESCRIPTION
**Pull request by samarth-1729**
#### References to other Issues or PRs or Relevant literature
https://towardsdatascience.com/svm-implementation-from-scratch-python-2db2fc52e5c2

#### Brief description of what is fixed or changed
Implemented Support Vector machine

Reference #5

### CODE REVIEW

**Comment by TarunTomar122** [comment]
@samarth-1729  you need to insert a suitable test case and an example file in your commit to prove your implementation. Rest LGTM.

**Review by TarunTomar122 — COMMENTED** [review]
LGTM for now!

**Comment by rohansingh9001** [comment]
Use flake8 to check for formatting in your root directory.

Rest you need to add an example file in the root directory to show how to use your model.

**Comment by kwanit1142** [comment]
Due to Prolonged Inactivity, the Pull Request would be closed.

**Pull request closed without merging**
