### PR TITLE
Algorithms Implemented Table Update: neater now

### LINKED ISSUE #68: Improve Readme
We need to write and link every algorithm and function implemented in our library in the readme.
Currently, there is no way to know what functions and algorithms have been implemented, so it is very hard for newcomers to understand the repository. We want to fix that by providing links in the Readme to all the functions and algorithms that are currently implemented  :)

### PR DESCRIPTION
**Pull request by GoldExplosion**
#### Brief description of what is fixed or changed
This PR updates the Algorithms Implemented table to look neat. Fixes #68

### CODE REVIEW

**Comment by agrawalshubham01** [comment]
Currently I am not willing to merge, as it would be better to move each of these to individual files

**Comment by kwanit1142** [comment]
@GoldExplosion Update your fork and then make changes, because day by day, new implementations are being added or changed.

**Comment by GoldExplosion** [comment]
> @GoldExplosion Update your fork and then make changes, because day by day, new implementations are being added or changed.

i think it was up to date when i created a PR

**Comment by kwanit1142** [comment]
Looks Good to Me

**Review by kwanit1142 — APPROVED** [review]

**Pull request merged**
