### PR TITLE
Two activation functions added

### PR DESCRIPTION
**Pull request by parva-jain**
#### Other comments
This PR corresponds to issue #69. Added functions are Binary step function and Swish activation function.

### CODE REVIEW

**Comment by rohansingh9001** [comment]
@parva-jain you can see the build errors by going to [this link](https://travis-ci.org/github/RoboticsClubIITJ/ML-DL-implementation/builds/747937767?utm_source=github_status&utm_medium=notification).

Also, the logic of the activation functions seems correct, however, make sure to add parameters like the threshold in the step activation function. So that a user can control after which value the activation function steps. 

You can do the same with the swish activation, there is a parameter called beta, which you can add as an optional parameter in the function.

Also, can you rename the binary step function to the `unit_step` function? As it would make it consistent with unit step signals as most people are used to that name.

Rest LGTM

**Comment by parva-jain** [comment]
> @parva-jain you can see the build errors by going to [this link](https://travis-ci.org/github/RoboticsClubIITJ/ML-DL-implementation/builds/747937767?utm_source=github_status&utm_medium=notification).
> 
> Also, the logic of the activation functions seems correct, however, make sure to add parameters like the threshold in the step activation function. So that a user can control after which value the activation function steps. 
> 
> You can do the same with the swish activation, there is a parameter called beta, which you can add as an optional parameter in the function.
> 
> Also, can you rename the binary step function to the `unit_step` function? As it would make it consistent with unit step signals as most people are used to that name.
> 
> Rest LGTM

I will do the said changes, but I have gone through that build error link and doesn't understand what's wrong, so need ur help on that.

**Comment by agrawalshubham01** [comment]
@parva-jain 
> I will do the said changes, but I have gone through that build error link and doesn't understand what's wrong, so need ur help on that.

We are using flake8 for checking docstyle errors. There are 3 errors raised in your PR. You can run locally by installing flake8.

```
./MLlib/activations.py:166:1: E302 expected 2 blank lines, found 1
./MLlib/activations.py:186:1: W293 blank line contains whitespace
./MLlib/activations.py:187:1: E302 expected 2 blank lines, found 1
```

These are the errors, the first and third one is because when there change class and then function then it is expected to leave 2 lines but you left only one so leave one more line at line 166 and 187 of MLlib/activation.py
The second fuction is because you have left white space in empty line i.e there are spacebars pressed in between in line 186 of MLlib/activation.py, this is also checked ion flake8 that no white space is expected.

I think doing this would solve your problems. Also try configuring your code editor whichever you use that would make your lives simpler as this would be taken care by editor.

**Comment by parva-jain** [comment]
> @parva-jain
> 
> > I will do the said changes, but I have gone through that build error link and doesn't understand what's wrong, so need ur help on that.
> 
> We are using flake8 for checking docstyle errors. There are 3 errors raised in your PR. You can run locally by installing flake8.
> 
> ```
> ./MLlib/activations.py:166:1: E302 expected 2 blank lines, found 1
> ./MLlib/activations.py:186:1: W293 blank line contains whitespace
> ./MLlib/activations.py:187:1: E302 expected 2 blank lines, found 1
> ```
> 
> These are the errors, the first and third one is because when there change class and then function then it is expected to leave 2 lines but you left only one so leave one more line at line 166 and 187 of MLlib/activation.py
> The second fuction is because you have left white space in empty line i.e there are spacebars pressed in between in line 186 of MLlib/activation.py, this is also checked ion flake8 that no white space is expected.
> 
> I think doing this would solve your problems. Also try configuring your code editor whichever you use that would make your lives simpler as this would be taken care by editor.

Got it, will take care of this from now onwards.

**Comment by parva-jain** [comment]
Hey @rohansingh9001, I'm new to git and GitHub and I have messed up in this branch (merge conflicts are there which I'm not able to solve) so can I open a new PR with the same content I want to contribute?

**Comment by agrawalshubham01** [comment]
> I'm new to git and GitHub and I have messed up in this branch (merge conflicts are there which I'm not able to solve) so can I open a new PR with the same content I want to contribute?

@parva-jain if only merge conflict is the problem then do `git pull  https://github.com/RoboticsClubIITJ/ML-DL-implementation.git` and then push this to your repo. This would solve the merge conflict problem.

**Review by agrawalshubham01 — APPROVED** [review]

**Pull request merged**
