### PR TITLE
Added examples for 2 models (Enhancement)

### PR DESCRIPTION
**Pull request by rohansingh9001**
Changed learning rate of Adam to improve learning in Linear Regression example.

Separated examples of Logistic Regression and Linear Regression.

### CODE REVIEW

**Review by TarunTomar122 — APPROVED** [review]
LGTM ;)

**Comment by agrawalshubham01** [comment]
@rohansingh9001 I would suggest create a folder for examples and we can dump all examples there. This would make our code more modulated.  @TarunTomar122 views?

**Comment by TarunTomar122** [comment]
> @rohansingh9001 I would suggest create a folder for examples and we can dump all examples there. This would make our code more modulated. @TarunTomar122 views?

agreed and noted. This shall be done!

**Comment by rohansingh9001** [comment]
@agrawalshubham01 we can do this in the next PR

For now there are only 2 examples.

**Review by agrawalshubham01 — APPROVED** [review]

**Pull request merged**
