### PR TITLE
Wrote the test for ReLU function

### PR DESCRIPTION
**Pull request by SomshuvraBasu**
Wrote the Test for ReLU function

### CODE REVIEW

**Comment by SusimRoy** [comment]
test_Relu() function too big. Can be optimized to fewer lines.

**Comment by SomshuvraBasu** [comment]
Okay, will revert back with it.

**Comment by SomshuvraBasu** [comment]
Have Optimised it now by shortening the code.

**Comment by SusimRoy** [comment]
LGTM.

**Review by SusimRoy — APPROVED** [review]

**Comment by rohansingh9001** [comment]
@SomshuvraBasu Some lint errors are present in your code.

Always check if you python code is formatted correctly by running the flake8 utility. To check details of why your code is failing [see this](https://github.com/RoboticsClubIITJ/ML-DL-implementation/actions/runs/3769713273/jobs/6412511107).

**Pull request closed without merging**
