### PR TITLE
Fixed the unit step function

### PR DESCRIPTION
**Pull request by parva-jain**
This PR corresponds to issue #99. Fixed the implementation of unit step function.

### CODE REVIEW

**Comment by kwanit1142** [comment]
Before pull requesting, did you tested the program that whether your output is desired now?

**Comment by kwanit1142** [comment]
Kindly add test for the function, AS FROM NOW , adding test will be compulsory , else Pull Request will not get merged

**Comment by parva-jain** [comment]
> Before pull requesting, did you tested the program that whether your output is desired now?

yes

**Comment by parva-jain** [comment]
> Kindly add test for the function, AS FROM NOW , adding test will be compulsory , else Pull Request will not get merged

Alright. One more thing, my points in the leaderboard are not getting updated and no one responding to my messages in gitter. Please acknowledge if u are one of the maintainers.

**Comment by agrawalshubham01** [comment]
@parva-jain don't worry about your leaderboard it will be updated. Rohan was a busy ig he will update withing a day or 2.

**Comment by parva-jain** [comment]
> @parva-jain don't worry about your leaderboard it will be updated. Rohan was a busy ig he will update withing a day or 2.

Is there something wrong with this PR?

**Review by rohansingh9001 — APPROVED** [review]
LGTM

**Pull request merged**
