### PR TITLE
Adding issue templates

### LINKED ISSUE #77: Add issue template
Can I make issue templates to enhance the workflow of the repository?

### PR DESCRIPTION
**Pull request by Kerveyfelix**
#### References to other Issues or PRs or Relevant literature

Fixes #77 

#### Brief description of what is fixed or changed
Add two files for issue template:
1. Bug report
2. Feature request

#### Other comments
Kindly review the pr.

### CODE REVIEW

**Comment by agrawalshubham01** [comment]
@Kerveyfelix Kindly share the reference, as I haven't these kind of issue_templates in any public repo i.e the design you have used for feature_request/bug_report.

**Comment by Kerveyfelix** [comment]
I have used this repo's issue templates: https://github.com/harsh-9in/Blogger/tree/master/.github/ISSUE_TEMPLATE

**Review by agrawalshubham01 — APPROVED** [review]
Cool, merging it.

**Comment by Kerveyfelix** [comment]
Thank you

**Pull request merged**
