### PR TITLE
added Gaussian Naives Bayes

### PR DESCRIPTION
**Pull request by Saptashrungi**
#### Brief description of what is fixed or changed
The dataset used contains of Height, Weight and Foot-size of males and females. Given the class, we predict the gender using Gaussian Naive Bayes.

#### Other comments
References used: 
https://chrisalbon.com/machine_learning/naive_bayes/naive_bayes_classifier_from_scratch/
https://hackernoon.com/implementation-of-gaussian-naive-bayes-in-python-from-scratch-c4ea64e3944d

### CODE REVIEW

**Comment by Saptashrungi** [comment]
In one line, in gaussian_naive_bayes_example.py, if I format it using PEP8 its exceeding characters in a line and on reducing the characters it (Travis CI) gives error.

**Comment by agrawalshubham01** [comment]
> In one line, in gaussian_naive_bayes_example.py, if I format it using PEP8 its exceeding characters in a line and on reducing the characters it (Travis CI) gives error.

@Saptashrungi Better define for all files .

**Comment by agrawalshubham01** [comment]
> In one line, in gaussian_naive_bayes_example.py, if I format it using PEP8 its exceeding characters in a line and on reducing the characters it (Travis CI) gives error.

I think we should create a `.flake8` file and address all the exceptions in the same file.

Suggestions?? @TarunTomar122 @Saptashrungi @rohansingh9001

**Comment by TarunTomar122** [comment]
@agrawalshubham01  you know i would appreciate it. You should do that.

**Review by TarunTomar122 — APPROVED** [review]
LGTM

**Comment by TarunTomar122** [comment]
@Saptashrungi  final fix commit is out of order?! why is it behaving like that any insights.? @rohansingh9001

**Comment by Saptashrungi** [comment]
Out of order? I committed after the comment and it passed all checks.

**Comment by TarunTomar122** [comment]
:+1:

**Pull request merged**
