### PR TITLE
K_Means_Clustering

### PR DESCRIPTION
**Pull request by kwanit1142**
#### References to other Issues or PRs or Relevant literature
https://towardsdatascience.com/k-means-clustering-from-scratch-6a9d19cafc25

#### Brief description of what is fixed or changed

Implemented K-Means-Clustering Model, with its custom Dataset.

### CODE REVIEW

**Comment by TarunTomar122** [comment]
@kwanit1142  look good to me! let's see if @rohansingh9001 has anything to comment otherwise we'll merge it!

**Comment by rohansingh9001** [comment]
@TarunTomar122 merge this if it works. The empty print statements can be replaced by \n strings to reduce clutter. Rest LGTM.

**Comment by kwanit1142** [comment]
yes, like in later stages of updating and including more indicative curves, we can replace those empty print statements by \n strings.

**Comment by TarunTomar122** [comment]
@kwanit1142  LGTM. Cheers

**Review by TarunTomar122 — APPROVED** [review]

**Pull request merged**
