### PR TITLE
Evaluation metrics

### PR DESCRIPTION
**Pull request by Prachi0203**

### CODE REVIEW

**Comment by rohansingh9001** [comment]
@Prachi0203 in your code, you have used the zip() function which returns a list which might not be the most optimal code in this case. Use some NumPy array compatible functions like hstack or vstack instead. 

The spelling of false on line 22 is incorrect.

Also, your code formatting is not following PEP 8 standards. Go to [this link](https://travis-ci.org/github/RoboticsClubIITJ/ML-DL-implementation/builds/747785562) to see where the errors are, all the errors start from line 232. To check for these errors locally use flake8 or some suitable formatting checker.

Also, move the file from the Examples folder to MLlib.
The destination of the file should be MLlib/metrics.py.

Please make these changes so that I can check your code further. The logic for the functions seems correct, however, I can check them after you make these changes.
Thanks for Contributing!

**Comment by kwanit1142** [comment]
@Prachi0203 a more optimized approach for file is to make class with variables contained in self_init() and score definitions , just using those variables. I hope it will give a valuable insight to you.

**Comment by Prachi0203** [comment]
Yeah sure I will make changes. This was my first contribution.... :) so if
I have any query how can I ask?

**Comment by rohansingh9001** [comment]
> Yeah sure I will make changes. This was my first contribution.... :) so thank you for insights


Feel free to use the Gitter Channel to ask any doubts. Any maintainer of our repository may answer your queries.

**Comment by kwanit1142** [comment]
@Prachi0203 , any updates regarding implementation ?

**Comment by Prachi0203** [comment]
Yes I have made the required changes let me know if any changes are required. Metrics I have added are accuracy, precision, recall, f1, tpr, fpr. I will try to add some other metrics too but I want to be sure if it can be merged or not.

**Comment by kwanit1142** [comment]
Due to prolonged Inactivity, I am freeing the Issue to be solved by others.

**Pull request closed without merging**
