### PR TITLE
Added A Simple Deep Learning Library Using NumPy Only.

### PR DESCRIPTION
**Pull request by q-viper**
#12 
#### [Implementation of Neural Network](https://github.com/RoboticsClubIITJ/ML-DL-implementation/issues/12) 

* Follow test.py file under quark for testing the Neural Network. 
* Adds slightly like Keras fashion by adding layers Sequentially.
* All are OOP.

### CODE REVIEW

**Comment by TarunTomar122** [comment]
Hello @q-viper. There seem to be some problems regarding your commits. First thing that i noticed is that you have written the same activation functions redundantly again in ur commit. You should have used them from our repo. Also some checks have failed as you can clearly see from the commit. I am hereby requesting you to make appropriate changes to your commit and if possible i would suggest you to reuse code as much as possible. I hope you understand me and looking forward to your corporation.

**Comment by q-viper** [comment]
Hi @TarunTomar122, sorry for the problems. I will try to do as your suggestions.

**Review by rohansingh9001 — APPROVED** [review]
We are merging for now, I will correct any problems later if it occurs and will implement a better integration. Thanks for your contribution!

**Comment by agrawalshubham01** [comment]
@rohansingh9001 @q-viper I think this folder should be in subfolder to MLlib and also thould be renamed. Comments?

**Comment by q-viper** [comment]
@agrawalshubham01 yeah the folder quark should be under MLlib and ofcourse rename it as required. But I will be grateful to on contributors list.

**Comment by q-viper** [comment]
@agrawalshubham01 yeah this quark should be under MLlib.  And please rename it as required. Really glad and proud to be on contributors list.

**Pull request merged**
