### PR TITLE
Added Visualize class

### PR DESCRIPTION
**Pull request by PawanSuryavanshi95**

### CODE REVIEW

**Comment by rohansingh9001** [comment]
This PR has the same problem as PR #13 where the graph is plotted once after the training is completed while is can be plotted live which updates for each and every epoch. @uakarsh was already assigned this issue. He has already made a PR #13 with the same functionality as this.

**Comment by TarunTomar122** [comment]
@rohansingh9001  i think this class that he wrote is good enough. Why do you want the graph to update on every epoch? Even for standard frameworks the graph is shown once the training is done!

**Comment by PawanSuryavanshi95** [comment]
Let me have a look at this, it can be shown during training too.

**Comment by rohansingh9001** [comment]
@uakarsh is working on live updates. For now we can merge this PR.

**Comment by rohansingh9001** [comment]
@PawanSuryavanshi95 rename the example file to what is in the repository now. The names of the files have to been updated from example.py to linear_example.py and logistic_example.py.

Rest LGTM.

**Review by TarunTomar122 — APPROVED** [review]

**Comment by TarunTomar122** [comment]
@rohansingh9001  @PawanSuryavanshi95  Can we do this for all models?!

**Comment by rohansingh9001** [comment]
The visualize class added here should be usable for all models and not just one model. @PawanSuryavanshi95 @TarunTomar122.

If that is not the case, this may need to be updated. Also, there are merge conflicts. That needs to be fixed as well.

**Comment by TarunTomar122** [comment]
Closed due to Inactivity!

**Pull request closed without merging**
